#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

if [[ $(xrandr --query | grep 'HDMI-1 connected') ]];
then
  xrandr --output eDP-1 --primary --mode 1366x768 --output HDMI-1 --mode 1360x768
  bspc monitor eDP-1 -d 1 2 3 4 5
  bspc monitor HDMI-1 -d 6 7 8 9 10
else
    if [[ $(xrandr --query | grep 'eDP-1 connected') ]];
    then
      xrandr -s 1366x768
    else
      xrandr -s 1360x768
    fi
    bspc monitor -d 1 2 3 4 5 6 7 8 9 10
fi

bspc config border_width         0
bspc config window_gap           0

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' follow=on
bspc rule -a $BROWSER desktop='^2'
bspc rule -a Signal desktop='^6'
bspc rule -a Chromium desktop='^7'
bspc rule -a Zathura state=tiled
bspc rule -a mplayer2 state=floating
bspc rule -a mpv state=tiled
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Virt-manager desktop='^9'

signal-desktop &
$BROWSER &
feh --bg-fill --no-fehbg ~/.config/.bg.jpg &
xsetroot -cursor_name left_ptr &

# mapping menu key to Super_R and caps to escape
xmodmap ~/.config/myrc/Xmodmap &

~/.config/polybar/launch.sh &
blueman-applet &
dunst &
$TERMINAL -e tmux &
virt-manager &
