#!/bin/sh

bookmark="$(xclip -o)"
file="$XDG_DESKTOP_DIR/bookmarks/bookmarks"

if grep -q "^$bookmark$" "$file"; then
  notify-send "Oops!" "Already bookmarked!"
else
  notify-send "bookmark added!" $bookmark
  echo "$bookmark" >> "$file"
fi
