# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false

# A minimal left prompt
#format = """$directory$character"""
format = """$all"""

# move the rest of the prompt to the right
#right_format = """$all"""
right_format = """"""

[character]
success_symbol = "[➜](bold green)"

#[character]
#symbol = "❯❯"

[line_break]
disabled = true

[rust]
disabled = false
symbol = "󱘗 "
#format = '[$symbol($version )]($style)'
style = "white"
format = '[$symbol]($style)'

[lua]
disabled = false
style = "white"
symbol = " "
format = '[$symbol]($style)'

#[jobs]
#number_threshold = 0

[cmd_duration]
disabled = false

#[directory]
#prefix = ""

[git_branch]
symbol = ""
style = "bold yellow"
#format = "$symbol[$branch(:$remote_branch)]($style)"
format = "[$symbol]($style)"

[git_commit]
disabled = true

[git_metrics]
disabled = false

[git_status]
format = '([$all_status$ahead_behind]($style))'
style = "bold yellow"

[package]
disabled = true
